package vistas;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Label;
import javafx.scene.control.TextArea;
import javafx.scene.control.TextField;
import javafx.scene.image.ImageView;
import javafx.scene.input.MouseEvent;
import logica.MensajeYComentario;
import logica.Producto;
import logica.Vendedor;

public class PanelComentariosController implements Initializable {
	@FXML
	private Label lblNombreProducto;
	@FXML
	private TextField txtComentario;
	@FXML
	private ImageView btnEnviar;
	@FXML
	private TextArea areaComentario;
	private Producto producto;
	private Vendedor quienComenta;
	private Main main;

	// Event Listener on ImageView[#btnEnviar].onMouseClicked
	@FXML
	public void enviarComnetario(MouseEvent event) {
		// TODO Autogenerated
		MensajeYComentario comentario = new MensajeYComentario(this.quienComenta, txtComentario.getText());
		this.producto.getComentarios().agregar(comentario);
		main.guardarArchivo(Main.ruta);
		areaComentario.setText(comentario.toString());
	}

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub

	}

	public void setPrincipal(Producto producto, Vendedor quienComenta, Main main) {
		this.producto = producto;
		this.quienComenta = quienComenta;
		this.main = main;
		lblNombreProducto.setText(this.producto.getNombre());

	}
}
