package vistas;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.image.ImageView;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.BorderPane;
import javafx.stage.Modality;
import javafx.stage.Stage;
import logica.Producto;
import logica.Vendedor;

public class PanelProductosContactosController implements Initializable {
	@FXML
	private BorderPane center;
	@FXML
	private Label lblContacto;
	@FXML
	private Label lblFecha;
	@FXML
	private ImageView btnLikes;
	@FXML
	private Label lblCantLikes;
	@FXML
	private Label lblCantComentarios;
	@FXML
	private ImageView btnComentario;
	@FXML
	private Label lblNombre;
	@FXML
	private Button btnVerDetalles;
	private Main main;
	private Vendedor dueñoProducto;
	private Vendedor vendedor;
	private Producto producto;

	// Event Listener on ImageView[#btnLikes].onMouseClicked
	@FXML
	public void darLike(MouseEvent event) {
		// TODO Autogenerated
		if (main.getRed().obtenerContactos(vendedor).contains(dueñoProducto)) {
			if (!producto.getMeGusta().contains(vendedor)) {
				this.producto.getMeGusta().agregar(this.vendedor);
				main.guardarArchivo(Main.ruta);
				System.out.println("like");
				lblCantLikes.setText("" + this.producto.obtenerCantMeGusta());
			} else {
				main.mostrarNotificacion(" Ya le diste like a esta publicacion ", "../Imagener/alerta.png");
			}

		} else {
			main.mostrarNotificacion("Debes ser un contacto de " + dueñoProducto.getNombre() + " para dar Like",
					"../Imagener/alerta.png");
			System.out.println("No ta");
		}

	}

	// Event Listener on ImageView[#btnComentario].onMouseClicked
	@FXML
	public void dejarComentario(MouseEvent event) {
		// TODO Autogenerated
		if (main.getRed().obtenerContactos(vendedor).contains(dueñoProducto)) {
			mostrarComentarios(vendedor, producto);
			lblCantComentarios.setText("" + this.producto.obtenerCantComentarios());

		} else {
			main.mostrarNotificacion(
					"Debes se un contacto de " + dueñoProducto.getNombre() + " para dejar un comentario",
					"../Imagener/alerta.png");
			System.out.println("No ta");
		}

	}

	// Event Listener on Button[#btnVerDetalles].onMouseClicked
	@FXML
	public void verDetalles(MouseEvent event) {
		// TODO Autogenerated
		mostrarDetalleProducto(this.producto);

	}

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub

	}

	public void setPrincipal(Main main, Vendedor dueñoProducto, Producto producto, Vendedor vendedor) {
		// TODO Auto-generated method stub
		this.main = main;
		this.dueñoProducto = dueñoProducto;
		this.producto = producto;
		this.vendedor = vendedor;
		lblContacto.setText(this.dueñoProducto.getNombre());
		lblNombre.setText(this.producto.getNombre());
		lblFecha.setText(this.producto.getFecha() + " - " + this.producto.getHora());
		lblCantLikes.setText("" + this.producto.obtenerCantMeGusta());
		lblCantComentarios.setText("" + this.producto.obtenerCantComentarios());

	}

	public void mostrarDetalleProducto(Producto p) {
		try {
			System.out.println("Click" + p.getNombre());
			FXMLLoader cargador = new FXMLLoader();
			cargador.setLocation(getClass().getResource("PanelLikesYComentarios.fxml"));
			BorderPane vista = (BorderPane) cargador.load();

			PanelLikesYComentariosController control = cargador.getController();
			control.setPrincipal(main, p);

			Stage escenario = new Stage();
			escenario.initModality(Modality.WINDOW_MODAL);
			escenario.initOwner(main.getEscenarioPrincipal());

			Scene escena = new Scene(vista);
			escenario.setScene(escena);

			escenario.showAndWait();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public void mostrarComentarios(Vendedor vendedor, Producto p) {
		try {
			System.out.println("Click" + p.getNombre());
			FXMLLoader cargador = new FXMLLoader();
			cargador.setLocation(getClass().getResource("PanelComentarios.fxml"));
			BorderPane vista = (BorderPane) cargador.load();

			PanelComentariosController control = cargador.getController();
			control.setPrincipal(p, vendedor, main);

			Stage escenario = new Stage();
			escenario.initModality(Modality.WINDOW_MODAL);
			escenario.initOwner(main.getEscenarioPrincipal());

			Scene escena = new Scene(vista);
			escenario.setScene(escena);

			escenario.showAndWait();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

}
