package vistas;

import java.net.URL;
import java.util.ResourceBundle;

import estructuras.ErrorExisteNodo;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.TextField;
import javafx.scene.image.ImageView;
import javafx.scene.input.MouseEvent;
import logica.CamposVaciosEx;
import logica.Vendedor;

public class VentanaCrearVendedorController implements Initializable {
	@FXML
	private ImageView btnAtras;
	@FXML
	private TextField txtTelefono;
	@FXML
	private TextField txtNombre;
	@FXML
	private TextField txtDireccion;
	@FXML
	private TextField txtCorreo;
	@FXML
	private ImageView btnGuardar;
	private Main main;
	private Vendedor vendedor;
	public static String ruta = "src/utilidades/persistencia.xml";

	// Event Listener on ImageView[#btnAtras].onMouseClicked
	@FXML
	public void atras(MouseEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on ImageView[#btnGuardar].onMouseClicked
	@FXML
	public void guardarVendedor(MouseEvent event) {
		// TODO Autogenerated
		// System.out.println("hola");
		try {
			String nombre = txtNombre.getText();
			String correo = txtCorreo.getText();
			String direccion = txtDireccion.getText();
			String telefono = txtTelefono.getText();
			if (nombre.trim().equals("") || correo.trim().equals("") || direccion.trim().equals("")
					|| telefono.trim().equals("")) {
				throw new CamposVaciosEx("Por favor llene todos los campos");
			}

			vendedor = new Vendedor(nombre, telefono, direccion, correo);
			if (main.getRed().AgregarVendedor(vendedor)) {
				limpiarCampos();
				main.guardarArchivo(Main.ruta);
			}

		} catch (ErrorExisteNodo existeNod) {
			// TODO: handle exception
			main.mostrarNotificacion("El Vendedor ya existe", "../Imagener/alerta.png");
		} catch (CamposVaciosEx camposVacios) {
			// TODO: handle exception
			main.mostrarNotificacion(camposVacios.getMessage(), "../Imagener/alerta.png");
		}

	}

	private void limpiarCampos() {
		txtNombre.setText("");
		txtCorreo.setText("");
		txtDireccion.setText("");
		txtTelefono.setText("");
		main.mostrarNotificacion("El vendedor se ha agregado", "../Imagener/vendedorNuevo.png");
	}

	@Override
	public void initialize(URL location, ResourceBundle resources) {

	}

	public void setPrincipal(Main main) {
		this.main = main;

	}

}
