package vistas;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.BorderPane;
import javafx.stage.Modality;
import javafx.stage.Stage;

public class VentanaInicialController implements Initializable {
	@FXML
	private BorderPane center;
	@FXML
	private Button btnAgregarVendedor;
	@FXML
	private Button btnEntrarRed;
	@FXML
	private Button btnEstadisticas;
	private Stage inicialStage;
	private Main main;

	// Event Listener on Button[#btnAgregarVendedor].onMouseClicked
	@FXML
	public void agregarVendedor(MouseEvent event) {
		// TODO Autogenerated
		mostraVistaRegistro();

	}

	// Event Listener on Button[#btnEntrarRed].onMouseClicked
	@FXML
	public void entrarRed(MouseEvent event) {
		// TODO Autogenerated
		mostrarUsuarios();
	}

	// Event Listener on Button[#btnEstadisticas].onMouseClicked
	@FXML
	public void estadisticas(MouseEvent event) {
		// TODO Autogenerated
		mostrarEstadisticas();

	}

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub

	}

	public void setPrincipal(Main main) {
		this.main = main;

	}

	/*
	 * public void mostraVistaRegistro() { try { FXMLLoader cargador = new
	 * FXMLLoader();
	 * cargador.setLocation(getClass().getResource("VentanaCrearVendedor.fxml"));
	 * BorderPane vista = (BorderPane) cargador.load();
	 * 
	 * VentanaCrearVendedorController control = cargador.getController();
	 * control.setPrincipal(main);
	 * 
	 * Stage escenario = new Stage(); escenario.initModality(Modality.WINDOW_MODAL);
	 * escenario.initOwner(main.getEscenarioPrincipal()); Scene escena = new
	 * Scene(vista); escenario.setScene(escena);
	 * 
	 * escenario.showAndWait();
	 * 
	 * } catch (Exception e) { e.printStackTrace(); } }
	 */

	public void mostraVistaRegistro() {
		try {
			FXMLLoader cargador = new FXMLLoader();
			cargador.setLocation(getClass().getResource("VentanaCrearVendedor.fxml"));

			BorderPane panelRegistro = cargador.load();
			VentanaCrearVendedorController control = cargador.getController();
			control.setPrincipal(main);
			center.setCenter(panelRegistro);

		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	public void mostrarUsuarios() {
		try {
			FXMLLoader cargador = new FXMLLoader();
			cargador.setLocation(getClass().getResource("VentanaUsuarios.fxml"));
			BorderPane vista = (BorderPane) cargador.load();

			VentanaUsuariosController control = cargador.getController();
			control.setPrincipal(main, this);

			Stage escenario = new Stage();
			escenario.initModality(Modality.WINDOW_MODAL);
			escenario.initOwner(main.getEscenarioPrincipal());

			Scene escena = new Scene(vista);
			escenario.setScene(escena);

			escenario.showAndWait();

		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public void mostrarEstadisticas() {
		try {
			FXMLLoader cargador = new FXMLLoader();
			cargador.setLocation(getClass().getResource("VentanaEstadisticas.fxml"));

			AnchorPane panelContactos = cargador.load();
			VentanaEstadisticasController control = cargador.getController();
			control.setPrinicipal(main);
			center.setCenter(panelContactos);
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	public Stage getStageInicial() {
		return this.inicialStage;
	}

}
